app:
  name: 'Strafforts'
  demo_path: '/athletes/9123806'
  description: 'An Analytics App for Strava Best Efforts, PBs/PRs and Races'
  emailer:
    default_sender_name: 'Yi Zeng'
    default_sender_email: 'support@strafforts.com'
  facebook_page_url: 'https://www.facebook.com/strafforts'
  global_message: <%= ENV['GLOBAL_MESSAGE'] %>
  html_meta_description: 'An analytics app that allow athletes to analyze their visualized Strava best efforts, personal bests and races data in tables and charts.'
  html_meta_description_for_athletes: 'Visualized Strava best efforts, PBs/PRs and races data for '
  html_meta_keywords: 'strava,strafforts,bestefforts,pb,races,running,data,visualizer,analytics'
  production_url: 'https://www.strafforts.com'
  title: 'Strafforts - An Analytics App for Strava Best Efforts, PBs/PRs and Races'
  version: <%= ENV['APP_VERSION'] %>
strava:
  api_auth_authorize_url: 'https://www.strava.com/oauth/authorize'
  api_auth_deauthorize_url: 'https://www.strava.com/oauth/deauthorize'
  api_auth_token_url: 'https://www.strava.com/oauth/token'
  api_client_id: <%= ENV['STRAVA_API_CLIENT_ID'] %>
  athletes_base_url: 'https://www.strava.com/athletes'
